#!/bin/bash
echo "Escolha uma opção acima: "
echo "< 1 > Somar "
echo "< 2 > Subtração "
echo "< 3 > Multiplicação "
echo "< 4 > Divisão "
echo "< 5 > Raiz Quadrada " 
echo "< 6 > Potencia " 

  read equacao
  echo "Digite um numero: "
  read num1
  echo "Didite um numero: "
  read num2
  
  
  function somar() {
  resultado=$(($num1+num2)) 
  echo $resultado
  } 
  
  function subtrair() {
  resultado=$(($num1-num2)) 
  echo $resultado
  }
  
  function multiplicar() {
  resultado=$(($num1*num2)) 
  echo $resultado
  }
  
  function dividir() {
  resultado=$(($num1/num2)) 
  echo $resultado
  }
  
  function raiz() {
  resultado=$((sqrt$num1)) 
  echo $resultado
  }
  
  function potencia() {
  resultado=$(($num1**num2 )) 
  echo $resultado
  }
  
  if [ $equacao -eq 1 ]; then
    #resultado=$[num1+num2]
    resultado=$( somar num1 num2 )
  elif [ $equacao -eq 2 ]; then
    resultado=$( subtrair num1 num2 )
  elif [ $equacao -eq 3 ]; then
    resultado=$( multiplicar num1 num2 )
  elif [ $equacao -eq 4 ]; then
    resultado=$( dividir num1 num2 ) 
  elif [ $equacao -eq 5 ]; then
    resultado=$( echo "sqrt($num1)" | bc )
  elif [ $equacao -eq 6 ]; then
    resultado=$( potencia num1 num2 )
    
  else 
   echo "Opção invalida."
  fi
   echo "O resultado é: $resultado"
    
